"use client";

import {useMutation, useQuery, useQueryClient} from "@tanstack/react-query";
import {ArrowLeft, FileClock, FileText, Hash, LoaderCircle, MessageSquareText, Trash2, UploadCloud, Workflow} from "lucide-react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useRef, useState} from "react";
import {toast} from "sonner";
import {ConfirmDeleteDialog} from "@/components/confirm-delete-dialog";
import {IngestionPipeline} from "@/components/ingestion-pipeline";
import {PageHeader} from "@/components/page-header";
import {StatusBadge} from "@/components/status-badge";
import {Button} from "@/components/ui/button";
import {ErrorState} from "@/components/ui/error-state";
import {LoadingState} from "@/components/ui/loading-state";
import {apiFetch} from "@/lib/api";
import type {Document, DocumentVersion, IngestionRun, Project} from "@/lib/types";
import {cn, relativeTime} from "@/lib/utils";

type Tab = "overview" | "versions" | "runs" | "metadata";

export function DocumentDetail({projectId, documentId, initialTab = "overview"}: {projectId: string; documentId: string; initialTab?: Tab}) {
  const router = useRouter();
  const queryClient = useQueryClient();
  const inputRef = useRef<HTMLInputElement>(null);
  const [tab, setTab] = useState<Tab>(initialTab);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const document = useQuery({queryKey: ["document", documentId], queryFn: () => apiFetch<Document>(`/documents/${documentId}`)});
  const project = useQuery({queryKey: ["project", projectId], queryFn: () => apiFetch<Project>(`/projects/${projectId}`)});
  const versions = useQuery({queryKey: ["document-versions", documentId], queryFn: () => apiFetch<DocumentVersion[]>(`/documents/${documentId}/versions`)});
  const runs = useQuery({queryKey: ["ingestion-runs", projectId], queryFn: () => apiFetch<IngestionRun[]>(`/ingest/runs?project_id=${projectId}&limit=100`)});
  const documentRuns = (runs.data ?? []).filter((run) => run.document_id === documentId);
  const upload = useMutation({mutationFn: async (file: File) => {if (file.name !== document.data?.filename) throw new Error(`Choose a file named ${document.data?.filename} so the backend creates a new version of this document.`); const form = new FormData(); form.set("project_id", projectId); form.set("chunker", versions.data?.[0]?.chunker_id ?? "paragraph"); form.set("file", file); return apiFetch<{ingestion_run_id: string}>("/ingest/file", {method: "POST", body: form});}, onSuccess: async (result) => {await Promise.all([queryClient.invalidateQueries({queryKey: ["document-versions", documentId]}), queryClient.invalidateQueries({queryKey: ["ingestion-runs", projectId]})]); toast.success("New document version accepted"); router.push(`/projects/${projectId}/runs/${result.ingestion_run_id}`);}, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to upload version")});
  const remove = useMutation({mutationFn: () => apiFetch(`/documents/${documentId}`, {method: "DELETE"}), onSuccess: async () => {await queryClient.invalidateQueries({queryKey: ["documents", projectId]}); toast.success("Document deleted"); router.replace(`/projects/${projectId}/documents`);}, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to delete document")});
  if (document.isLoading) return <LoadingState label="Loading document" rows={5} />;
  if (document.isError || !document.data) return <ErrorState title="Document could not be loaded" description="The document may have been deleted or may belong to another tenant." onRetry={() => void document.refetch()} />;
  const doc = document.data;
  return <div className="mx-auto max-w-6xl space-y-6"><Link href={`/projects/${projectId}/documents`} className="inline-flex items-center gap-1.5 text-[10px] text-[#71847b] hover:text-white"><ArrowLeft className="size-3" />Back to workspace</Link><PageHeader eyebrow={project.data?.name ?? "Project"} title={doc.filename ?? "Untitled document"} description="Inspect document status, immutable versions, pipeline runs, and durable metadata." actions={<><input ref={inputRef} type="file" className="hidden" onChange={(event) => {const file = event.target.files?.[0]; if (file) upload.mutate(file); event.currentTarget.value = "";}} /><Button variant="secondary" disabled={upload.isPending} onClick={() => inputRef.current?.click()}>{upload.isPending ? <LoaderCircle className="size-4 animate-spin" /> : <UploadCloud className="size-4" />}Upload new version</Button><Link href={`/projects/${projectId}/documents?document=${documentId}`} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[var(--accent)] px-4 text-sm font-medium text-[var(--ink-inverse)]"><MessageSquareText className="size-4" />Ask about this</Link></>} />
    <div className="flex gap-1 overflow-x-auto border-b border-white/[0.08]">{([['overview',FileText],['versions',FileClock],['runs',Workflow],['metadata',Hash]] as [Tab,typeof FileText][]).map(([value,Icon]) => <button key={value} onClick={() => setTab(value)} className={cn("flex h-10 shrink-0 items-center gap-2 border-b px-3 text-[11px] capitalize", tab === value ? "border-[var(--accent)] text-[var(--accent-hover)]" : "border-transparent text-[#64736d] hover:text-white")}><Icon className="size-3.5" />{value}</button>)}</div>
    {tab === "overview" ? <div className="grid gap-4 md:grid-cols-3"><div className="rounded-xl border border-white/[0.08] bg-[var(--surface)] p-5 md:col-span-2"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Document status</h2><StatusBadge status={doc.status} /></div><dl className="mt-5 grid gap-4 text-xs sm:grid-cols-2"><div><dt className="text-[#64736d]">Source type</dt><dd className="mt-1 capitalize">{doc.source_type ?? "Unknown"}</dd></div><div><dt className="text-[#64736d]">File type</dt><dd className="mt-1">{doc.mime_type ?? doc.extension ?? "Unknown"}</dd></div><div><dt className="text-[#64736d]">Current version</dt><dd className="mono mt-1 text-[10px]">{doc.current_version_id ?? "No active version"}</dd></div><div><dt className="text-[#64736d]">Last updated</dt><dd className="mt-1">{relativeTime(doc.updated_at)}</dd></div></dl></div><div className="rounded-xl border border-red-400/10 bg-[var(--surface)] p-5"><h2 className="text-sm font-semibold">Danger zone</h2><p className="mt-2 text-[10px] leading-5 text-[#71847b]">Deleting removes the logical document and its indexed chunks. Version rollback is not supported.</p><Button className="mt-4" variant="danger" size="sm" onClick={() => setConfirmDelete(true)}><Trash2 className="size-3.5" />Delete document</Button></div></div> : null}
    {tab === "versions" ? versions.isLoading ? <LoadingState label="Loading versions" rows={3} /> : versions.isError ? <ErrorState title="Version history could not be loaded" description="The version endpoint returned an error." onRetry={() => void versions.refetch()} /> : versions.data?.length ? <ol className="relative space-y-3 before:absolute before:bottom-5 before:left-5 before:top-5 before:w-px before:bg-white/[0.08]">{versions.data.map((version) => <li key={version.document_version_id} className="relative ml-10 rounded-xl border border-white/[0.08] bg-[var(--surface)] p-4"><span className="absolute -left-[30px] top-5 flex size-5 items-center justify-center rounded-full border border-[var(--accent-border)] bg-[var(--surface)] text-[8px] text-[var(--accent)]">{version.version_number}</span><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="text-xs font-semibold">Version {version.version_number}</h3><p className="mt-1 text-[9px] text-[#64736d]">Created {relativeTime(version.created_at)}</p></div><StatusBadge status={version.status} /></div><dl className="mt-4 grid gap-3 text-[9px] sm:grid-cols-2"><div><dt className="text-[#53625b]">Content hash</dt><dd className="mono mt-1 break-all text-[#83948c]">{version.content_hash}</dd></div><div><dt className="text-[#53625b]">Chunker / embedding</dt><dd className="mono mt-1 text-[#83948c]">{version.chunker_id ?? "—"} · {version.embedding_model ?? "—"}</dd></div></dl>{version.error_message ? <p className="mt-3 rounded-lg bg-red-400/[0.05] p-2 text-[9px] text-red-200">{version.error_message}</p> : null}</li>)}</ol> : <p className="text-sm text-[#71847b]">No versions are available.</p> : null}
    {tab === "runs" ? runs.isLoading ? <LoadingState label="Loading runs" rows={3} /> : documentRuns.length ? <div className="space-y-3">{documentRuns.map((run) => <IngestionPipeline key={run.ingestion_run_id} run={run} document={doc} projectId={projectId} compact />)}</div> : <p className="text-sm text-[#71847b]">No ingestion runs are available for this document.</p> : null}
    {tab === "metadata" ? <div className="overflow-hidden rounded-xl border border-white/[0.08] bg-[var(--surface)]">{Object.entries(doc).map(([key,value]) => <div key={key} className="grid gap-2 border-b border-white/[0.07] px-4 py-3 last:border-0 sm:grid-cols-[160px_1fr]"><span className="text-[10px] text-[#64736d]">{key.replaceAll("_", " ")}</span><code className="mono break-all text-[10px] text-[#b8c5bf]">{value === null ? "—" : String(value)}</code></div>)}</div> : null}
    <ConfirmDeleteDialog open={confirmDelete} onClose={() => setConfirmDelete(false)} name={doc.filename ?? doc.document_id} title={`Delete ${doc.filename ?? "document"}?`} consequences="The document, its versions, and indexed chunks will no longer be available. Query logs may retain audit metadata." isPending={remove.isPending} onConfirm={() => remove.mutate()} />
  </div>;
}
