"use client";

import {useQuery} from "@tanstack/react-query";
import {AlertCircle, CheckCircle2, ChevronDown, Circle, CircleStop, Copy, FilePlus2, History, LoaderCircle, RefreshCw, Search, Send, Settings2, SlidersHorizontal, Sparkles, X} from "lucide-react";
import {useRef, useState} from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import {toast} from "sonner";
import {apiFetch} from "@/lib/api";
import {consumeSSE} from "@/lib/sse";
import type {QueryHistoryItem, QueryTrace, RetrievalTrace, StreamEvent} from "@/lib/types";
import {cn} from "@/lib/utils";
import type {WorkspaceDocument} from "@/components/workspace/workspace-data";

type ActivityStatus = "pending" | "active" | "done" | "error";
type ActivityId = "received" | "retrieving" | "reranking" | "generating" | "saving" | "citations";
type ActivityStep = {id: ActivityId; label: string; detail: string; status: ActivityStatus};
type Message = {id: string; role: "user" | "assistant"; text: string; complete: boolean; activity?: ActivityStep[]; activityCollapsed?: boolean; sources?: RetrievalTrace[]; timestamp: string; error?: string; question?: string};
const activityTemplate: ActivityStep[] = [
  {id: "received", label: "Received question", detail: "Prepared the project and document scope.", status: "pending"},
  {id: "retrieving", label: "Retrieved evidence", detail: "Searched indexed document chunks with the selected filters.", status: "pending"},
  {id: "reranking", label: "Ranked sources", detail: "Ordered candidate passages for answer grounding.", status: "pending"},
  {id: "generating", label: "Generated response", detail: "Composed an answer using retrieved evidence.", status: "pending"},
  {id: "saving", label: "Saved query trace", detail: "Persisted provider metadata and retrieval audit data.", status: "pending"},
  {id: "citations", label: "Verified citations", detail: "Loaded source links for answer inspection.", status: "pending"},
];
const suggestions = ["Summarize the key findings", "Explain the main methodology", "What are the important risks?", "List the documented requirements"];

function createActivity(active: ActivityId = "received"): ActivityStep[] {
  return setActivityStatus(activityTemplate, active);
}

function setActivityStatus(steps: ActivityStep[], active: ActivityId, error = false): ActivityStep[] {
  const activeIndex = steps.findIndex((step) => step.id === active);
  return steps.map((step, index) => {
    const status: ActivityStatus = error && step.id === active ? "error" : index < activeIndex ? "done" : step.id === active ? "active" : "pending";
    return {...step, status};
  });
}

function completeActivity(steps: ActivityStep[], through: ActivityId = "citations"): ActivityStep[] {
  const throughIndex = steps.findIndex((step) => step.id === through);
  return steps.map((step, index) => ({...step, status: index <= throughIndex ? "done" : "pending"}));
}

function failActivity(steps: ActivityStep[]): ActivityStep[] {
  const activeIndex = steps.findIndex((step) => step.status === "active");
  return steps.map((step, index) => ({...step, status: index === activeIndex ? "error" : step.status}));
}

function CitationChip({source, onClick}: {source: RetrievalTrace; onClick: () => void}) {
  return <button onClick={onClick} className="source-chip inline-flex min-h-7 max-w-full items-center gap-1 rounded-md border border-[var(--accent-border)] bg-[var(--accent-soft)] px-2 text-xs font-medium text-[var(--accent-hover)] hover:border-[var(--border-hover)]" title={source.text ?? undefined}><FilePlus2 className="size-3 shrink-0" /><span className="min-w-0 truncate">{source.document_name?.replace(/\.(pdf|docx|xlsx)$/i, "") || "Source"} · p.{source.page_start ?? "—"}</span></button>;
}

function AssistantMessage({message, onCitation, onTrace, onRegenerate, onToggleActivity}: {message: Message; onCitation: (source: RetrievalTrace) => void; onTrace: () => void; onRegenerate: (question: string) => void; onToggleActivity: () => void}) {
  return <div className="group flex gap-3"><div className="mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-lg border border-[var(--accent-border)] bg-[var(--accent-soft)] text-[var(--accent)]"><Sparkles className="size-4" /></div><div className="message-content min-w-0 flex-1"><div className="mb-2 flex items-center gap-2"><span className="text-xs font-semibold">RAGForge Assistant</span><span className="text-xs text-[var(--ink-faint)]">{message.timestamp}</span></div>
    {message.activity?.length ? <div className="mb-4 rounded-lg border border-white/[0.07] bg-white/[0.02] p-3" role="status" aria-live="polite">
      <div className="flex items-center justify-between gap-3"><p className="text-xs font-medium text-[var(--ink-secondary)]">Execution trace</p>{message.complete ? <button onClick={onToggleActivity} className="flex h-6 items-center gap-1 rounded px-1.5 text-[10px] text-[var(--ink-muted)] hover:bg-white/5 hover:text-white"><ChevronDown className={cn("size-3 transition", !message.activityCollapsed && "rotate-180")} />{message.activityCollapsed ? "Show" : "Hide"}</button> : null}</div>
      {!message.activityCollapsed ? <ol className="mt-3 space-y-2">
        {message.activity.map((step) => <li key={step.id} className="flex gap-2.5">
          <span className={cn("mt-0.5 flex size-4 shrink-0 items-center justify-center rounded-full border", step.status === "done" ? "border-[var(--success-border)] bg-[var(--success-soft)] text-[#b9cce2]" : step.status === "active" ? "border-[var(--accent-border)] text-[var(--accent)]" : step.status === "error" ? "border-[var(--danger-border)] bg-[var(--danger-soft)] text-red-300" : "border-white/10 text-[var(--ink-faint)]")}>{step.status === "done" ? <CheckCircle2 className="size-3" /> : step.status === "active" ? <LoaderCircle className="size-3 animate-spin" /> : step.status === "error" ? <AlertCircle className="size-3" /> : <Circle className="size-2" />}</span>
          <span className="min-w-0"><span className={cn("block text-xs font-medium", step.status === "pending" ? "text-[var(--ink-muted)]" : "text-[var(--ink-secondary)]")}>{step.label}</span><span className="block text-[11px] leading-4 text-[var(--ink-faint)]">{step.detail}</span></span>
        </li>)}
      </ol> : null}
    </div> : null}
    {message.text ? <div className="markdown-answer text-sm leading-[1.65]"><ReactMarkdown remarkPlugins={[remarkGfm]}>{message.text}</ReactMarkdown></div> : null}
    {message.error ? <div role="alert" className="rounded-lg border border-red-400/20 bg-red-400/[0.07] p-3 text-xs leading-5 text-red-200">{message.error}</div> : null}
    {message.sources?.length ? <div className="mt-4 flex flex-wrap gap-1.5">{message.sources.filter((source) => source.used_in_answer).map((source) => <CitationChip key={source.retrieval_log_id} source={source} onClick={() => onCitation(source)} />)}<button onClick={onTrace} className="min-h-7 rounded-md px-2 text-xs text-[var(--ink-muted)] hover:bg-white/5 hover:text-white">View retrieval trace</button></div> : null}
    {message.complete && message.text ? <div className="mt-4 flex items-center gap-1 border-t border-white/[0.07] pt-2"><button aria-label="Copy answer" onClick={() => {void navigator.clipboard?.writeText(message.text); toast.success("Answer copied");}} className="icon-button size-7"><Copy className="size-3" /></button>{message.question ? <button aria-label="Regenerate answer" onClick={() => onRegenerate(message.question ?? "")} className="icon-button size-7"><RefreshCw className="size-3" /></button> : null}<button onClick={onTrace} className="ml-1 text-xs text-[var(--ink-muted)] hover:text-white">Retrieval details</button></div> : null}
  </div></div>;
}

function HistoryDrawer({projectId, onClose, onRestore}: {projectId: string; onClose: () => void; onRestore: (trace: QueryTrace) => void}) {
  const [search, setSearch] = useState("");
  const {data: items = [], isLoading, isError} = useQuery({queryKey: ["query-history", projectId], queryFn: () => apiFetch<QueryHistoryItem[]>(`/rag/projects/${projectId}/history?limit=100`)});
  async function restore(id: string) {try {onRestore(await apiFetch<QueryTrace>(`/rag/queries/${id}`));} catch (error) {toast.error(error instanceof Error ? error.message : "Unable to restore query");}}
  const filtered = items.filter((item) => `${item.question} ${item.answer ?? ""}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="absolute inset-y-0 right-0 z-50 flex w-full max-w-sm flex-col border-l border-white/10 bg-[var(--surface-muted)] shadow-2xl" role="dialog" aria-label="Query history"><div className="flex h-12 items-center justify-between border-b border-white/10 px-4"><div><h3 className="text-xs font-semibold">Query history</h3><p className="text-[8px] text-[#64736d]">Recent conversations in this project</p></div><button onClick={onClose} className="icon-button" aria-label="Close query history"><X className="size-3.5" /></button></div><div className="p-2"><label className="flex h-9 items-center gap-2 rounded-lg border border-white/[0.08] px-2"><Search className="size-3 text-[#64736d]" /><span className="sr-only">Search query history</span><input value={search} onChange={(event) => setSearch(event.target.value)} className="min-w-0 flex-1 bg-transparent text-[10px] outline-none" placeholder="Search query history" /></label></div><div className="overflow-y-auto px-2 pb-4">{isLoading ? <p className="p-4 text-center text-[9px] text-[#64736d]">Loading query history…</p> : isError ? <p className="p-4 text-center text-[9px] text-red-300">Query history could not be loaded.</p> : filtered.length ? filtered.map((item) => <button onClick={() => void restore(item.query_log_id)} key={item.query_log_id} className="mb-1 w-full rounded-lg p-3 text-left hover:bg-white/[0.03]"><h4 className="text-[10px] font-medium leading-4">{item.question}</h4><p className="mt-1 line-clamp-2 text-[9px] leading-4 text-[#71847b]">{item.answer ?? "This query did not produce an answer."}</p><p className="mt-2 text-[8px] text-[#53625b]">{new Date(item.created_at).toLocaleString()} · {item.model ?? "model unavailable"}</p></button>) : <p className="p-8 text-center text-[10px] text-[#64736d]">No matching query history.</p>}</div></div>;
}

export function AssistantPanel({projectId, projectName, documents, selectedIds, onRemoveSelected, onCitation, onOpenTrace}: {projectId: string; projectName: string; documents: WorkspaceDocument[]; selectedIds: string[]; onRemoveSelected: (id: string) => void; onCitation: (source: RetrievalTrace) => void; onOpenTrace: () => void}) {
  const [question, setQuestion] = useState(""); const [messages, setMessages] = useState<Message[]>([]); const [streaming, setStreaming] = useState(false); const [history, setHistory] = useState(false); const [settings, setSettings] = useState(false); const [provider, setProvider] = useState<"gemini" | "groq">("gemini"); const [useParentContext, setUseParentContext] = useState(true); const [includeContext, setIncludeContext] = useState(true);
  const controllerRef = useRef<AbortController | null>(null);
  const selected = documents.filter((document) => selectedIds.includes(document.document_id)); const indexedDocuments = documents.filter((document) => document.status === "indexed");
  function update(id: string, patch: Partial<Message> | ((message: Message) => Partial<Message>)) {setMessages((current) => current.map((message) => message.id === id ? {...message, ...(typeof patch === "function" ? patch(message) : patch)} : message));}
  async function loadTrace(assistantId: string, queryLogId: string) {try {const trace = await apiFetch<QueryTrace>(`/rag/queries/${queryLogId}`); update(assistantId, (message) => ({sources: trace.retrievals, activity: completeActivity(message.activity ?? activityTemplate)}));} catch {update(assistantId, (message) => ({activity: setActivityStatus(message.activity ?? activityTemplate, "citations", true)})); toast.error("The answer completed, but its retrieval trace could not be loaded.");}}
  async function send(forcedQuestion?: string) {
    const value = (forcedQuestion ?? question).trim(); if (!value || streaming) return; if (!indexedDocuments.length) {toast.error("Index at least one document before asking a question."); return;}
    const assistantId = crypto.randomUUID(); setMessages((current) => [...current, {id: crypto.randomUUID(), role: "user", text: value, complete: true, timestamp: "Now"}, {id: assistantId, role: "assistant", text: "", complete: false, timestamp: "Now", activity: createActivity(), question: value}]); setQuestion(""); setStreaming(true);
    const controller = new AbortController(); controllerRef.current = controller;
    try {
      const response = await fetch("/api/backend/rag/query/stream", {method: "POST", headers: {"Content-Type": "application/json", Accept: "text/event-stream"}, body: JSON.stringify({question: value, project_id: projectId, provider, document_id: selectedIds[0] || null, use_parent_context: useParentContext, include_context: includeContext}), signal: controller.signal});
      await consumeSSE(response, {onEvent: (event: StreamEvent) => {const activityMap: Record<string, ActivityId> = {"query.received": "received", "query.embedding": "retrieving", "query.retrieving": "retrieving", "query.reranking": "reranking", "query.generating": "generating"}; if (activityMap[event.event]) update(assistantId, (message) => ({activity: setActivityStatus(message.activity ?? activityTemplate, activityMap[event.event])})); if (event.event === "query.token" && typeof event.text === "string") setMessages((current) => current.map((message) => message.id === assistantId ? {...message, text: message.text + event.text, activity: setActivityStatus(message.activity ?? activityTemplate, "generating")} : message)); if (event.event === "query.completed") {update(assistantId, (message) => ({complete: true, activity: setActivityStatus(completeActivity(message.activity ?? activityTemplate, "saving"), "citations")})); if (typeof event.query_log_id === "string") void loadTrace(assistantId, event.query_log_id); else update(assistantId, (message) => ({activity: completeActivity(message.activity ?? activityTemplate, "saving")}));} if (event.event === "query.failed") update(assistantId, (message) => ({complete: true, activity: failActivity(message.activity ?? activityTemplate), error: typeof event.error === "string" ? event.error : "The query failed."}));}});
    } catch (error) {update(assistantId, (message) => ({complete: true, activity: failActivity(message.activity ?? activityTemplate), error: controller.signal.aborted ? "Generation stopped." : error instanceof Error ? error.message : "The query service is unavailable."}));} finally {setStreaming(false); controllerRef.current = null;}
  }
  return <section className="assistant-workspace relative grid h-full min-w-0 grid-rows-[auto_minmax(0,1fr)_auto] bg-[var(--background)]">
    <header className="assistant-header shrink-0 border-b border-white/[0.08] px-6 py-3"><div className="assistant-header-inner mx-auto flex w-full max-w-[860px] items-center justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><h2 className="text-sm font-semibold">RAGForge Assistant</h2><span className="hidden truncate text-xs text-[var(--ink-muted)] sm:inline">{projectName}</span></div><p className="mt-0.5 truncate text-xs text-[var(--ink-faint)]">Grounded in {selected.length ? selected[0]?.filename : `${indexedDocuments.length} indexed documents`}</p></div><div className="flex shrink-0 items-center gap-1"><button title="Query history" onClick={() => setHistory(true)} className="icon-button size-8"><History className="size-4" /></button><button onClick={() => setMessages([])} className="flex h-8 items-center gap-1 rounded-lg border border-white/[0.08] px-2.5 text-xs text-[var(--ink-muted)] hover:bg-white/5"><RefreshCw className="size-3" />New chat</button></div></div></header>
    <div className="conversation-scroll-area min-h-0 overflow-y-auto overscroll-contain px-6 py-6">{!messages.length ? <div className="conversation-container mx-auto flex h-full min-h-[340px] w-full max-w-[860px] flex-col items-center justify-center text-center"><div className="flex size-11 items-center justify-center rounded-xl border border-[var(--accent-border)] bg-[var(--accent-soft)] text-[var(--accent)]"><Sparkles className="size-5" /></div><h2 className="mt-4 text-lg font-semibold">Ask your knowledge base</h2><p className="mt-2 max-w-md text-sm leading-6 text-[var(--ink-muted)]">Stream a grounded answer, then open its citations to inspect the exact supporting chunks.</p>{indexedDocuments.length ? <div className="mt-5 grid w-full max-w-[620px] gap-2 sm:grid-cols-2">{suggestions.map((prompt) => <button key={prompt} onClick={() => setQuestion(prompt)} className="rounded-lg border border-white/[0.08] px-3 py-2.5 text-left text-xs text-[var(--ink-muted)] hover:border-[var(--accent-border)] hover:text-white">{prompt}</button>)}</div> : <p className="mt-4 rounded-lg border border-amber-400/20 bg-amber-400/[0.06] px-3 py-2 text-xs text-amber-200">Index a document before asking a question.</p>}</div> : <div className="conversation-container mx-auto w-full max-w-[860px] space-y-7">{messages.map((message) => message.role === "user" ? <div key={message.id} className="flex justify-end"><div className="max-w-[82%] rounded-xl rounded-br-sm border border-white/[0.08] bg-[var(--surface-raised)] px-4 py-3 text-sm leading-[1.65]">{message.text}</div></div> : <AssistantMessage key={message.id} message={message} onCitation={onCitation} onTrace={onOpenTrace} onRegenerate={(value) => void send(value)} onToggleActivity={() => update(message.id, {activityCollapsed: !message.activityCollapsed})} />)}</div>}</div>
    <div className="composer-region shrink-0 bg-gradient-to-t from-[var(--background)] via-[var(--background)] px-6 pb-[max(20px,env(safe-area-inset-bottom))] pt-4 max-h-[45dvh] overflow-visible"><div className="conversation-container mx-auto w-full max-w-[860px]">{selected.length ? <div className="mb-2 flex max-w-full gap-1.5 overflow-x-auto">{selected.map((doc) => <span key={doc.document_id} className="source-chip flex h-7 max-w-full shrink items-center gap-1 rounded-md border border-white/[0.08] bg-white/[0.045] px-2 text-xs text-[var(--ink-muted)]"><FilePlus2 className="size-3 shrink-0 text-[var(--accent)]" /><span className="min-w-0 truncate">{doc.filename}</span><button className="shrink-0 rounded text-[var(--ink-faint)] hover:text-white" onClick={() => onRemoveSelected(doc.document_id)} aria-label={`Remove ${doc.filename} from query scope`}><X className="size-3" /></button></span>)}</div> : null}<div className="relative rounded-xl border border-white/[0.13] bg-[var(--surface-muted)] shadow-xl focus-within:border-[var(--border-focus)]"><textarea value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => {if (event.key === "Enter" && !event.shiftKey) {event.preventDefault(); void send();}}} disabled={!indexedDocuments.length} placeholder="Ask a question about your knowledge base..." className="block min-h-12 max-h-32 w-full resize-none bg-transparent px-4 py-3 text-sm leading-6 outline-none placeholder:text-[var(--ink-faint)]" /><div className="flex items-center justify-between px-2.5 pb-2"><div className="flex items-center gap-1"><button onClick={() => setSettings((value) => !value)} aria-label="Retrieval settings" className={cn("icon-button size-8", settings && "bg-[var(--accent-soft)] text-[var(--accent)]")}><SlidersHorizontal className="size-3.5" /></button><label className="flex h-8 items-center gap-1 rounded px-1.5 text-xs text-[var(--ink-muted)]"><span className="sr-only">Model provider</span><span className="flex size-4 items-center justify-center rounded bg-[var(--info)] text-[8px] font-bold text-white">{provider === "gemini" ? "G" : "Q"}</span><select value={provider} onChange={(event) => setProvider(event.target.value as "gemini" | "groq")} className="bg-transparent outline-none"><option value="gemini">Gemini 2.5 Flash</option><option value="groq">Groq Llama 3.3</option></select><ChevronDown className="size-3" /></label></div>{streaming ? <button onClick={() => controllerRef.current?.abort()} aria-label="Stop generation" className="flex size-8 items-center justify-center rounded-lg bg-white/10"><CircleStop className="size-3.5" /></button> : <button onClick={() => void send()} disabled={!question.trim() || !indexedDocuments.length} aria-label="Send question" className="flex size-8 items-center justify-center rounded-lg bg-[var(--accent)] text-[var(--ink-inverse)] disabled:bg-white/[0.07] disabled:text-[#53625b]"><Send className="size-3.5" /></button>}</div>
      {settings ? <div className="absolute bottom-[calc(100%+8px)] left-0 w-72 rounded-lg border border-white/10 bg-[var(--surface-raised)] p-3 shadow-2xl"><div className="mb-2 flex items-center justify-between"><h3 className="text-xs font-semibold">Retrieval settings</h3><Settings2 className="size-3 text-[#64736d]" /></div><label className="flex items-center justify-between py-2 text-xs text-[var(--ink-muted)]">Use parent context<input type="checkbox" checked={useParentContext} onChange={(event) => setUseParentContext(event.target.checked)} className="accent-[var(--accent)]" /></label><label className="flex items-center justify-between py-2 text-xs text-[var(--ink-muted)]">Load citations after answer<input type="checkbox" checked={includeContext} onChange={(event) => setIncludeContext(event.target.checked)} className="accent-[var(--accent)]" /></label><p className="mt-2 border-t border-white/[0.07] pt-2 text-xs leading-5 text-[var(--ink-faint)]">The current API supports one document filter at a time. Selecting a document in the knowledge panel scopes retrieval to it.</p></div> : null}</div><p className="mt-2 text-center text-xs text-[var(--ink-faint)]">Verify important information against cited sources.</p></div></div>
    {history ? <HistoryDrawer projectId={projectId} onClose={() => setHistory(false)} onRestore={(trace) => {setMessages([{id: `${trace.query_log_id}-user`, role: "user", text: trace.question, complete: true, timestamp: new Date(trace.created_at).toLocaleTimeString([], {hour: "2-digit", minute: "2-digit"})}, {id: `${trace.query_log_id}-assistant`, role: "assistant", text: trace.answer ?? "", error: trace.answer ? undefined : "This query did not produce an answer.", complete: true, activity: completeActivity(activityTemplate), activityCollapsed: true, timestamp: new Date(trace.created_at).toLocaleTimeString([], {hour: "2-digit", minute: "2-digit"}), sources: trace.retrievals, question: trace.question}]); setHistory(false);}} /> : null}
  </section>;
}
