"use client";

import {useQuery} from "@tanstack/react-query";
import {ChevronDown, CircleStop, Copy, FilePlus2, History, LoaderCircle, RefreshCw, Search, Send, Settings2, SlidersHorizontal, Sparkles, X} from "lucide-react";
import {useRef, useState} from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import {toast} from "sonner";
import {apiFetch} from "@/lib/api";
import {consumeSSE} from "@/lib/sse";
import type {QueryHistoryItem, QueryTrace, RetrievalTrace, StreamEvent} from "@/lib/types";
import {cn} from "@/lib/utils";
import type {WorkspaceDocument} from "@/components/workspace/workspace-data";

type Message = {id: string; role: "user" | "assistant"; text: string; complete: boolean; stage?: string; sources?: RetrievalTrace[]; timestamp: string; error?: string; question?: string};
const stages = ["Understanding question", "Searching dense and sparse indexes", "Reranking sources", "Generating answer", "Saving query trace"];
const suggestions = ["Summarize the key findings", "Explain the main methodology", "What are the important risks?", "List the documented requirements"];

function CitationChip({source, onClick}: {source: RetrievalTrace; onClick: () => void}) {
  return <button onClick={onClick} className="inline-flex min-h-7 items-center gap-1 rounded-md border border-emerald-400/20 bg-emerald-400/[0.07] px-2 text-[9px] font-medium text-emerald-200 hover:border-emerald-400/40" title={source.text ?? undefined}><FilePlus2 className="size-2.5" />{source.document_name?.replace(/\.(pdf|docx|xlsx)$/i, "") || "Source"} · p.{source.page_start ?? "—"}</button>;
}

function AssistantMessage({message, onCitation, onTrace, onRegenerate}: {message: Message; onCitation: (source: RetrievalTrace) => void; onTrace: () => void; onRegenerate: (question: string) => void}) {
  return <div className="group flex gap-3"><div className="mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-lg border border-emerald-400/20 bg-emerald-400/10 text-emerald-300"><Sparkles className="size-4" /></div><div className="min-w-0 max-w-[780px] flex-1"><div className="mb-2 flex items-center gap-2"><span className="text-[11px] font-semibold">RAGForge Assistant</span><span className="text-[9px] text-[#53625b]">{message.timestamp}</span></div>
    {message.stage ? <div className="mb-3 rounded-lg border border-white/[0.07] bg-white/[0.02] p-3" role="status"><div className="flex items-center gap-2 text-[10px] text-[#a9b7b0]"><LoaderCircle className="size-3.5 animate-spin text-emerald-400" />{message.stage}</div><div className="mt-2 flex gap-1">{stages.map((stage) => <span key={stage} className={cn("h-0.5 flex-1 rounded-full", stages.indexOf(stage) <= stages.indexOf(message.stage ?? "") ? "bg-emerald-400" : "bg-white/10")} />)}</div></div> : null}
    {message.text ? <div className="markdown-answer text-[12px]"><ReactMarkdown remarkPlugins={[remarkGfm]}>{message.text}</ReactMarkdown></div> : null}
    {message.error ? <div role="alert" className="rounded-lg border border-red-400/20 bg-red-400/[0.07] p-3 text-[10px] leading-5 text-red-200">{message.error}</div> : null}
    {message.sources?.length ? <div className="mt-4 flex flex-wrap gap-1.5">{message.sources.filter((source) => source.used_in_answer).map((source) => <CitationChip key={source.retrieval_log_id} source={source} onClick={() => onCitation(source)} />)}<button onClick={onTrace} className="min-h-7 rounded-md px-2 text-[9px] text-[#71847b] hover:bg-white/5 hover:text-white">View retrieval trace →</button></div> : null}
    {message.complete && message.text ? <div className="mt-4 flex items-center gap-1 border-t border-white/[0.07] pt-2"><button aria-label="Copy answer" onClick={() => {void navigator.clipboard?.writeText(message.text); toast.success("Answer copied");}} className="icon-button size-7"><Copy className="size-3" /></button>{message.question ? <button aria-label="Regenerate answer" onClick={() => onRegenerate(message.question ?? "")} className="icon-button size-7"><RefreshCw className="size-3" /></button> : null}<button onClick={onTrace} className="ml-1 text-[9px] text-[#64736d] hover:text-white">Retrieval details</button></div> : null}
  </div></div>;
}

function HistoryDrawer({projectId, onClose, onRestore}: {projectId: string; onClose: () => void; onRestore: (trace: QueryTrace) => void}) {
  const [search, setSearch] = useState("");
  const {data: items = [], isLoading, isError} = useQuery({queryKey: ["query-history", projectId], queryFn: () => apiFetch<QueryHistoryItem[]>(`/rag/projects/${projectId}/history?limit=100`)});
  async function restore(id: string) {try {onRestore(await apiFetch<QueryTrace>(`/rag/queries/${id}`));} catch (error) {toast.error(error instanceof Error ? error.message : "Unable to restore query");}}
  const filtered = items.filter((item) => `${item.question} ${item.answer ?? ""}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="absolute inset-y-0 right-0 z-50 flex w-full max-w-sm flex-col border-l border-white/10 bg-[#0e1c17] shadow-2xl" role="dialog" aria-label="Query history"><div className="flex h-12 items-center justify-between border-b border-white/10 px-4"><div><h3 className="text-xs font-semibold">Query history</h3><p className="text-[8px] text-[#64736d]">Recent conversations in this project</p></div><button onClick={onClose} className="icon-button" aria-label="Close query history"><X className="size-3.5" /></button></div><div className="p-2"><label className="flex h-9 items-center gap-2 rounded-lg border border-white/[0.08] px-2"><Search className="size-3 text-[#64736d]" /><span className="sr-only">Search query history</span><input value={search} onChange={(event) => setSearch(event.target.value)} className="min-w-0 flex-1 bg-transparent text-[10px] outline-none" placeholder="Search query history" /></label></div><div className="overflow-y-auto px-2 pb-4">{isLoading ? <p className="p-4 text-center text-[9px] text-[#64736d]">Loading query history…</p> : isError ? <p className="p-4 text-center text-[9px] text-red-300">Query history could not be loaded.</p> : filtered.length ? filtered.map((item) => <button onClick={() => void restore(item.query_log_id)} key={item.query_log_id} className="mb-1 w-full rounded-lg p-3 text-left hover:bg-white/[0.03]"><h4 className="text-[10px] font-medium leading-4">{item.question}</h4><p className="mt-1 line-clamp-2 text-[9px] leading-4 text-[#71847b]">{item.answer ?? "This query did not produce an answer."}</p><p className="mt-2 text-[8px] text-[#53625b]">{new Date(item.created_at).toLocaleString()} · {item.model ?? "model unavailable"}</p></button>) : <p className="p-8 text-center text-[10px] text-[#64736d]">No matching query history.</p>}</div></div>;
}

export function AssistantPanel({projectId, projectName, documents, selectedIds, onRemoveSelected, onCitation, onOpenTrace}: {projectId: string; projectName: string; documents: WorkspaceDocument[]; selectedIds: string[]; onRemoveSelected: (id: string) => void; onCitation: (source: RetrievalTrace) => void; onOpenTrace: () => void}) {
  const [question, setQuestion] = useState(""); const [messages, setMessages] = useState<Message[]>([]); const [streaming, setStreaming] = useState(false); const [history, setHistory] = useState(false); const [settings, setSettings] = useState(false); const [provider, setProvider] = useState<"gemini" | "groq">("gemini"); const [useParentContext, setUseParentContext] = useState(true); const [includeContext, setIncludeContext] = useState(true);
  const controllerRef = useRef<AbortController | null>(null);
  const selected = documents.filter((document) => selectedIds.includes(document.document_id)); const indexedDocuments = documents.filter((document) => document.status === "indexed");
  function update(id: string, patch: Partial<Message>) {setMessages((current) => current.map((message) => message.id === id ? {...message, ...patch} : message));}
  async function loadTrace(assistantId: string, queryLogId: string) {try {const trace = await apiFetch<QueryTrace>(`/rag/queries/${queryLogId}`); update(assistantId, {sources: trace.retrievals});} catch {toast.error("The answer completed, but its retrieval trace could not be loaded.");}}
  async function send(forcedQuestion?: string) {
    const value = (forcedQuestion ?? question).trim(); if (!value || streaming) return; if (!indexedDocuments.length) {toast.error("Index at least one document before asking a question."); return;}
    const assistantId = crypto.randomUUID(); setMessages((current) => [...current, {id: crypto.randomUUID(), role: "user", text: value, complete: true, timestamp: "Now"}, {id: assistantId, role: "assistant", text: "", complete: false, timestamp: "Now", stage: stages[0], question: value}]); setQuestion(""); setStreaming(true);
    const controller = new AbortController(); controllerRef.current = controller;
    try {
      const response = await fetch("/api/backend/rag/query/stream", {method: "POST", headers: {"Content-Type": "application/json", Accept: "text/event-stream"}, body: JSON.stringify({question: value, project_id: projectId, provider, document_id: selectedIds[0] || null, use_parent_context: useParentContext, include_context: includeContext}), signal: controller.signal});
      await consumeSSE(response, {onEvent: (event: StreamEvent) => {const stageMap: Record<string,string> = {"query.received": stages[0], "query.retrieving": stages[1], "query.reranking": stages[2], "query.generating": stages[3]}; if (stageMap[event.event]) update(assistantId, {stage: stageMap[event.event]}); if (event.event === "query.token" && typeof event.text === "string") setMessages((current) => current.map((message) => message.id === assistantId ? {...message, text: message.text + event.text} : message)); if (event.event === "query.completed") {update(assistantId, {complete: true, stage: undefined}); if (typeof event.query_log_id === "string") void loadTrace(assistantId, event.query_log_id);} if (event.event === "query.failed") update(assistantId, {complete: true, stage: undefined, error: typeof event.error === "string" ? event.error : "The query failed."});}});
    } catch (error) {update(assistantId, {complete: true, stage: undefined, error: controller.signal.aborted ? "Generation stopped." : error instanceof Error ? error.message : "The query service is unavailable."});} finally {setStreaming(false); controllerRef.current = null;}
  }
  return <section className="relative flex h-full min-w-0 flex-col bg-[#07110d]">
    <div className="flex h-[49px] shrink-0 items-center justify-between border-b border-white/[0.08] px-3 lg:px-4"><div><div className="flex items-center gap-2"><h2 className="text-[13px] font-semibold">RAGForge Assistant</h2><span className="hidden text-[9px] text-[#64736d] sm:inline">{projectName}</span></div><p className="mt-0.5 text-[8px] text-[#64736d]">Grounded in {selected.length ? selected[0]?.filename : `${indexedDocuments.length} indexed documents`}</p></div><div className="flex items-center gap-1"><button title="Query history" onClick={() => setHistory(true)} className="icon-button size-7"><History className="size-3.5" /></button><button onClick={() => setMessages([])} className="flex h-7 items-center gap-1 rounded-lg border border-white/[0.08] px-2 text-[8px] text-[#a9b7b0] hover:bg-white/5"><RefreshCw className="size-2.5" />New chat</button></div></div>
    <div className="min-h-0 flex-1 overflow-y-auto px-4 py-5 sm:px-6 lg:px-8">{!messages.length ? <div className="flex h-full min-h-[340px] flex-col items-center justify-center text-center"><div className="flex size-11 items-center justify-center rounded-xl border border-emerald-400/20 bg-emerald-400/10 text-emerald-300"><Sparkles className="size-5" /></div><h2 className="mt-4 text-lg font-semibold">Ask your knowledge base</h2><p className="mt-2 max-w-md text-[11px] leading-5 text-[#71847b]">Stream a grounded answer, then open its citations to inspect the exact supporting chunks.</p>{indexedDocuments.length ? <div className="mt-5 grid w-full max-w-lg gap-2 sm:grid-cols-2">{suggestions.map((prompt) => <button key={prompt} onClick={() => setQuestion(prompt)} className="rounded-lg border border-white/[0.08] px-3 py-2.5 text-left text-[10px] text-[#a9b7b0] hover:border-emerald-400/20 hover:text-white">{prompt}</button>)}</div> : <p className="mt-4 rounded-lg border border-amber-400/20 bg-amber-400/[0.06] px-3 py-2 text-[9px] text-amber-200">Index a document before asking a question.</p>}</div> : <div className="mx-auto max-w-[820px] space-y-7">{messages.map((message) => message.role === "user" ? <div key={message.id} className="flex justify-end"><div className="max-w-[82%] rounded-xl rounded-br-sm border border-white/[0.08] bg-[#11221b] px-3.5 py-2.5 text-[11px] leading-5">{message.text}</div></div> : <AssistantMessage key={message.id} message={message} onCitation={onCitation} onTrace={onOpenTrace} onRegenerate={(value) => void send(value)} />)}</div>}</div>
    <div className="shrink-0 bg-gradient-to-t from-[#07110d] via-[#07110d] px-3 pb-[max(.75rem,env(safe-area-inset-bottom))] pt-2 sm:px-5"><div className="mx-auto max-w-[840px]">{selected.length ? <div className="mb-2 flex gap-1.5 overflow-x-auto">{selected.map((doc) => <span key={doc.document_id} className="flex h-6 shrink-0 items-center gap-1 rounded bg-white/[0.045] px-2 text-[8px] text-[#93a39c]"><FilePlus2 className="size-2.5 text-emerald-300" /><span className="max-w-40 truncate">{doc.filename}</span><button onClick={() => onRemoveSelected(doc.document_id)} aria-label={`Remove ${doc.filename} from query scope`}><X className="size-2.5" /></button></span>)}</div> : null}<div className="relative rounded-xl border border-white/[0.13] bg-[#0e1c17] shadow-xl focus-within:border-emerald-400/35"><textarea value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => {if (event.key === "Enter" && !event.shiftKey) {event.preventDefault(); void send();}}} disabled={!indexedDocuments.length} placeholder="Ask a question about your knowledge base…" className="block min-h-16 max-h-36 w-full resize-none bg-transparent px-3.5 py-3 text-[11px] leading-5 outline-none placeholder:text-[#53625b]" /><div className="flex items-center justify-between px-2 pb-2"><div className="flex items-center gap-1"><button onClick={() => setSettings((value) => !value)} aria-label="Retrieval settings" className={cn("icon-button size-7", settings && "bg-emerald-400/10 text-emerald-300")}><SlidersHorizontal className="size-3" /></button><label className="flex h-7 items-center gap-1 rounded px-1.5 text-[8px] text-[#71847b]"><span className="sr-only">Model provider</span><span className="flex size-3 items-center justify-center rounded bg-[#4285f4] text-[7px] font-bold text-white">{provider === "gemini" ? "G" : "Q"}</span><select value={provider} onChange={(event) => setProvider(event.target.value as "gemini" | "groq")} className="bg-transparent outline-none"><option value="gemini">Gemini 2.5 Flash</option><option value="groq">Groq Llama 3.3</option></select><ChevronDown className="size-2.5" /></label></div>{streaming ? <button onClick={() => controllerRef.current?.abort()} aria-label="Stop generation" className="flex size-8 items-center justify-center rounded-lg bg-white/10"><CircleStop className="size-3.5" /></button> : <button onClick={() => void send()} disabled={!question.trim() || !indexedDocuments.length} aria-label="Send question" className="flex size-8 items-center justify-center rounded-lg bg-emerald-400 text-[#052116] disabled:bg-white/[0.07] disabled:text-[#53625b]"><Send className="size-3.5" /></button>}</div>
      {settings ? <div className="absolute bottom-[calc(100%+8px)] left-0 w-72 rounded-lg border border-white/10 bg-[#13251e] p-3 shadow-2xl"><div className="mb-2 flex items-center justify-between"><h3 className="text-[10px] font-semibold">Retrieval settings</h3><Settings2 className="size-3 text-[#64736d]" /></div><label className="flex items-center justify-between py-2 text-[9px] text-[#a9b7b0]">Use parent context<input type="checkbox" checked={useParentContext} onChange={(event) => setUseParentContext(event.target.checked)} className="accent-emerald-400" /></label><label className="flex items-center justify-between py-2 text-[9px] text-[#a9b7b0]">Load citations after answer<input type="checkbox" checked={includeContext} onChange={(event) => setIncludeContext(event.target.checked)} className="accent-emerald-400" /></label><p className="mt-2 border-t border-white/[0.07] pt-2 text-[8px] leading-4 text-[#53625b]">The current API supports one document filter at a time. Selecting a document in the knowledge panel scopes retrieval to it.</p></div> : null}</div><p className="mt-1.5 text-center text-[8px] text-[#40524a]">Verify important information against cited sources.</p></div></div>
    {history ? <HistoryDrawer projectId={projectId} onClose={() => setHistory(false)} onRestore={(trace) => {setMessages([{id: `${trace.query_log_id}-user`, role: "user", text: trace.question, complete: true, timestamp: new Date(trace.created_at).toLocaleTimeString([], {hour: "2-digit", minute: "2-digit"})}, {id: `${trace.query_log_id}-assistant`, role: "assistant", text: trace.answer ?? "", error: trace.answer ? undefined : "This query did not produce an answer.", complete: true, timestamp: new Date(trace.created_at).toLocaleTimeString([], {hour: "2-digit", minute: "2-digit"}), sources: trace.retrievals, question: trace.question}]); setHistory(false);}} /> : null}
  </section>;
}
