"use client";

import {Check, ChevronDown, ChevronUp, Cloud, File, FileSpreadsheet, FileText, FolderInput, Globe2, MoreHorizontal, RefreshCw, Search, Settings2, Trash2, UploadCloud} from "lucide-react";
import Link from "next/link";
import {useMemo, useRef, useState} from "react";
import {StatusBadge} from "@/components/status-badge";
import type {Chunker, IngestionRun} from "@/lib/types";
import {cn, relativeTime} from "@/lib/utils";
import type {WorkspaceDocument} from "@/components/workspace/workspace-data";

function FileIcon({extension}: {extension: string | null}) {const Icon = extension === ".xlsx" || extension === ".csv" ? FileSpreadsheet : extension === ".docx" || extension === ".txt" ? FileText : File; return <span className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-[var(--info-soft)] text-[var(--info)]"><Icon className="size-4" /></span>;}

function DocumentRow({projectId, document, run, selected, scoped, onSelect, onScope, onOpen, onDelete, onRetry}: {projectId: string; document: WorkspaceDocument; run?: IngestionRun; selected: boolean; scoped: boolean; onSelect: () => void; onScope: () => void; onOpen: () => void; onDelete: () => void; onRetry: () => void}) {
  const [menu, setMenu] = useState(false);
  return <article data-selected={selected} className={cn("relative border-b border-white/[0.07] px-3 py-3 transition", selected ? "bg-[var(--accent-soft)] before:absolute before:inset-y-0 before:left-0 before:w-0.5 before:bg-[var(--accent)]" : "hover:bg-white/[0.025]")}>
    <div className="flex items-start gap-2.5"><button onClick={onScope} className={cn("mt-2 flex size-3.5 shrink-0 items-center justify-center rounded border", scoped ? "border-[var(--accent)] bg-[var(--accent)] text-[var(--ink-inverse)]" : "border-white/20")} aria-label={`${scoped ? "Remove" : "Use"} ${document.filename} ${scoped ? "from" : "as"} query scope`}>{scoped ? <Check className="size-2.5" /> : null}</button><FileIcon extension={document.extension} /><div className="min-w-0 flex-1"><button onClick={onSelect} className="block w-full min-w-0 text-left"><span className="document-name block truncate text-[13px] font-medium">{document.filename ?? "Untitled document"}</span><span className="document-metadata mt-1 flex flex-wrap items-center gap-1.5 text-xs text-[var(--ink-muted)]"><span className="capitalize">{document.source_type ?? "unknown"}</span><span>·</span><span>Updated {relativeTime(document.updated_at)}</span></span></button><div className="mt-1.5 flex flex-wrap items-center gap-2"><StatusBadge status={document.status} />{document.current_version_id ? <span className="mono max-w-24 truncate text-xs text-[var(--ink-faint)]" title={document.current_version_id}>v · {document.current_version_id}</span> : null}<button onClick={onOpen} className="rounded-md px-1.5 py-0.5 text-xs font-medium text-[var(--accent)] hover:bg-[var(--accent-soft)]">Open document</button></div></div><button onClick={() => setMenu((value) => !value)} className="icon-button size-7" aria-label={`Actions for ${document.filename}`} aria-expanded={menu}><MoreHorizontal className="size-3.5" /></button></div>
    {run && !["indexed","failed","cancelled"].includes(run.status) ? <div className="ml-[58px] mt-2 rounded-lg bg-[var(--info-soft)] p-2"><div className="flex items-center justify-between text-xs"><span className="text-[#c3cfdd]">Pipeline {run.status.replaceAll("_", " ")}</span><span className="text-[var(--ink-muted)]">{run.progress.qdrant ? "100" : run.progress.gold ? "78" : run.progress.silver ? "55" : run.progress.bronze ? "24" : "8"}%</span></div><div className="mt-1.5 h-1 rounded-full bg-white/[0.06]"><div className="h-full rounded-full bg-[var(--info)]" style={{width: `${run.progress.qdrant ? 100 : run.progress.gold ? 78 : run.progress.silver ? 55 : run.progress.bronze ? 24 : 8}%`}} /></div></div> : null}
    {run?.status === "failed" ? <div className="ml-[58px] mt-2 rounded-lg border border-red-400/10 bg-red-400/[0.04] p-2"><p className="line-clamp-2 text-xs leading-5 text-red-200/75">{run.error_message || "Processing failed without a diagnostic message."}</p><button onClick={onRetry} className="mt-1.5 flex items-center gap-1 text-xs font-medium text-red-300"><RefreshCw className="size-2.5" />Retry failed ingestion</button></div> : null}
    {menu ? <div className="popover right-3 top-10 w-44 p-1"><button className="menu-item w-full" onClick={() => {onOpen(); setMenu(false);}}>Open document</button><Link className="menu-item" href={`/projects/${projectId}/documents/${document.document_id}`}>Open details</Link><button className="menu-item w-full" onClick={() => {onScope(); setMenu(false);}}>Ask about this</button><Link className="menu-item" href={`/projects/${projectId}/documents/${document.document_id}`}>Upload new version</Link><Link className="menu-item" href={`/projects/${projectId}/documents/${document.document_id}/versions`}>View version history</Link>{run?.status === "failed" ? <button className="menu-item w-full" onClick={() => {onRetry(); setMenu(false);}}>Retry ingestion</button> : null}<button className="menu-item w-full text-red-300" onClick={() => {onDelete(); setMenu(false);}}><Trash2 className="size-3" />Delete document</button></div> : null}
  </article>;
}

export function DocumentPanel({projectId, projectName, documents, runs, chunkers, selectedIds, selectedDocumentId, onSelectDocument, onOpenDocument, onToggleSelected, onUpload, onUrl, onGDrive, onDelete, onRetry}: {projectId: string; projectName: string; documents: WorkspaceDocument[]; runs: IngestionRun[]; chunkers: Chunker[]; selectedIds: string[]; selectedDocumentId: string; onSelectDocument: (id: string) => void; onOpenDocument?: (id: string) => void; onToggleSelected: (id: string) => void; onUpload: (file: File, chunker: string) => Promise<void>; onUrl: (url: string, chunker: string) => Promise<void>; onGDrive: (fileId: string, accessToken: string, chunker: string) => Promise<void>; onDelete: (document: WorkspaceDocument) => void; onRetry: (run: IngestionRun) => void}) {
  const inputRef = useRef<HTMLInputElement>(null); const [search, setSearch] = useState(""); const [filter, setFilter] = useState("all"); const [uploadOpen, setUploadOpen] = useState(true); const [mode, setMode] = useState<"file"|"url"|"gdrive">("file"); const [file, setFile] = useState<File|null>(null); const [url, setUrl] = useState(""); const [driveId, setDriveId] = useState(""); const [driveToken, setDriveToken] = useState(""); const [chunker, setChunker] = useState(() => typeof window === "undefined" ? "paragraph" : localStorage.getItem(`ragforge:project:${projectId}:chunker`) ?? "paragraph"); const [uploading, setUploading] = useState(false);
  const filtered = useMemo(() => documents.filter((document) => (filter === "all" || document.status === filter) && (document.filename ?? "").toLowerCase().includes(search.toLowerCase())), [documents, filter, search]); const latestRun = new Map<string,IngestionRun>(); runs.forEach((run) => {if (!latestRun.has(run.document_id)) latestRun.set(run.document_id, run);});
  async function submit() {setUploading(true); try {if (mode === "file" && file) {await onUpload(file, chunker); setFile(null);} else if (mode === "url" && url.trim()) {await onUrl(url.trim(), chunker); setUrl("");} else if (mode === "gdrive" && driveId.trim() && driveToken.trim()) {await onGDrive(driveId.trim(), driveToken.trim(), chunker); setDriveId(""); setDriveToken("");}} finally {setUploading(false);}}
  const canSubmit = mode === "file" ? Boolean(file) : mode === "url" ? Boolean(url.trim()) : Boolean(driveId.trim() && driveToken.trim());
  return <section className="knowledge-panel flex h-full min-h-0 min-w-0 flex-col bg-[var(--surface)]"><div className="knowledge-section flex shrink-0 items-center justify-between border-b border-[var(--border)] px-3 py-3"><div className="min-w-0"><Link href="/projects" className="panel-label text-xs text-[var(--ink-muted)] hover:text-white">All projects</Link><h1 className="mt-0.5 truncate text-sm font-semibold">{projectName}</h1></div><Link href={`/projects/${projectId}/settings`} className="icon-button size-8" aria-label="Project settings"><Settings2 className="size-4" /></Link></div>
    <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain"><div className="knowledge-section border-b border-[var(--border)] px-3 py-3"><button onClick={() => setUploadOpen((value) => !value)} className="flex w-full items-center justify-between text-xs font-semibold"><span className="flex items-center gap-2"><UploadCloud className="size-3.5 text-[var(--accent)]" />Add knowledge</span>{uploadOpen ? <ChevronUp className="size-3.5 text-[#64736d]" /> : <ChevronDown className="size-3.5 text-[#64736d]" />}</button>{uploadOpen ? <div className="mt-3"><div className="grid grid-cols-3 gap-1 rounded-lg bg-white/[0.025] p-1">{([{id:"file",label:"File",icon:UploadCloud},{id:"url",label:"URL",icon:Globe2},{id:"gdrive",label:"Drive",icon:Cloud}] as const).map(({id,label,icon:Icon}) => <button key={id} onClick={() => setMode(id)} className={cn("flex h-8 items-center justify-center gap-1 rounded-md text-xs", mode === id ? "bg-[var(--surface-active)] text-[var(--accent-hover)]" : "text-[var(--ink-muted)]")}><Icon className="size-3" />{label}</button>)}</div>
      {mode === "file" ? <button onClick={() => inputRef.current?.click()} onDragOver={(event) => event.preventDefault()} onDrop={(event) => {event.preventDefault(); setFile(event.dataTransfer.files[0] ?? null);}} className="mt-2 flex min-h-[76px] w-full flex-col items-center justify-center rounded-lg border border-dashed border-white/[0.14] px-3 text-center hover:border-[var(--border-hover)]"><UploadCloud className="size-4 text-[var(--accent)]" /><span className="mt-1.5 max-w-full truncate text-xs text-[var(--ink-secondary)]">{file?.name ?? "Drop a file or browse"}</span><span className="mt-1 text-xs text-[var(--ink-faint)]">PDF, Office, CSV, HTML or text · 25 MB</span></button> : mode === "url" ? <label className="mt-2 block"><span className="sr-only">Public URL</span><input type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com/article" className="h-9 w-full rounded-lg border border-white/10 bg-white/[0.02] px-2.5 text-xs outline-none focus:border-[var(--border-hover)]" /></label> : <div className="mt-2 space-y-2"><input value={driveId} onChange={(event) => setDriveId(event.target.value)} placeholder="Google Drive file ID" className="h-9 w-full rounded-lg border border-white/10 bg-white/[0.02] px-2.5 text-xs outline-none" /><input type="password" value={driveToken} onChange={(event) => setDriveToken(event.target.value)} placeholder="Access token" className="h-9 w-full rounded-lg border border-white/10 bg-white/[0.02] px-2.5 text-xs outline-none" /></div>}<input ref={inputRef} type="file" className="hidden" accept=".pdf,.docx,.pptx,.xlsx,.csv,.txt,.md,.html,.htm" onChange={(event) => setFile(event.target.files?.[0] ?? null)} />
      <label className="mt-2 block"><span className="panel-label mb-1 block text-xs text-[var(--ink-muted)]">Chunking strategy</span><select value={chunker} onChange={(event) => {setChunker(event.target.value); localStorage.setItem(`ragforge:project:${projectId}:chunker`, event.target.value);}} className="h-9 w-full rounded-lg border border-white/[0.09] bg-white/[0.025] px-2 text-xs outline-none">{chunkers.filter((item) => item.id !== "multimodal").map((item) => <option key={item.id} value={item.id}>{item.name}{item.is_beta ? " · beta" : ""}</option>)}</select></label><button disabled={!canSubmit || uploading} onClick={() => void submit()} className="mt-2 h-9 w-full rounded-lg bg-[var(--accent)] text-xs font-semibold text-[var(--ink-inverse)] disabled:bg-white/[0.06] disabled:text-[#53625b]">{uploading ? "Submitting..." : mode === "file" ? "Start file ingestion" : "Add source"}</button></div> : null}</div>
      <div className="knowledge-section grid grid-cols-3 border-b border-[var(--border)] px-3 py-3 text-center"><div><b className="block text-sm">{documents.length}</b><span className="text-xs text-[var(--ink-muted)]">Documents</span></div><div><b className="block text-sm text-[var(--accent)]">{documents.filter((item) => item.status === "indexed").length}</b><span className="text-xs text-[var(--ink-muted)]">Indexed</span></div><div><b className="block text-sm text-[var(--info)]">{runs.filter((item) => !["indexed","failed","cancelled"].includes(item.status)).length}</b><span className="text-xs text-[var(--ink-muted)]">Active runs</span></div></div>
      <div className="knowledge-section sticky top-0 z-20 border-b border-[var(--border)] bg-[var(--surface)] px-3 py-3 backdrop-blur"><label className="flex h-9 items-center gap-1.5 rounded-lg border border-white/[0.08] px-2"><Search className="size-3 text-[#64736d]" /><span className="sr-only">Search documents</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search documents" className="min-w-0 flex-1 bg-transparent text-xs outline-none" /></label><div className="mt-2 flex gap-1">{["all","indexed","running","failed"].map((value) => <button key={value} onClick={() => setFilter(value)} className={cn("rounded-md px-2 py-1 text-xs capitalize", filter === value ? "bg-[var(--accent-soft)] text-[var(--accent)]" : "text-[var(--ink-muted)]")}>{value}</button>)}</div></div>
      <div>{filtered.map((document) => <DocumentRow key={document.document_id} projectId={projectId} document={document} run={latestRun.get(document.document_id)} selected={selectedDocumentId === document.document_id} scoped={selectedIds.includes(document.document_id)} onSelect={() => onSelectDocument(document.document_id)} onOpen={() => (onOpenDocument ?? onSelectDocument)(document.document_id)} onScope={() => onToggleSelected(document.document_id)} onDelete={() => onDelete(document)} onRetry={() => {const run = latestRun.get(document.document_id); if (run) onRetry(run);}} />)}</div>{!filtered.length ? <div className="flex flex-col items-center px-4 py-12 text-center"><FolderInput className="size-5 text-[#64736d]" /><p className="mt-2 text-xs">{documents.length ? "No matching documents" : "No documents yet"}</p><p className="mt-1 text-xs text-[var(--ink-muted)]">{documents.length ? "Try another filter." : "Use Add knowledge to upload a source."}</p></div> : null}
    </div>
  </section>;
}
